/**
 * Article image discovery — uses a pre-built JSON manifest instead of fs.
 * The manifest is generated by scripts/generate-image-manifest.ts before next build.
 * This avoids Vercel bundling 650MB of public/images/ into serverless functions.
 */

import manifest from './generated/image-manifest.json';

export interface MultiArtOption {
  path: string;
  option: number;
  model: string;
}

export interface ArticleImages {
  /** Best available image for hero display */
  heroImage: string | null;
  /** High-quality JPG from /images/articles/ */
  articleJpg: string | null;
  /** SVG from /images/articles/ */
  articleSvg: string | null;
  /** OG/social card SVG from /images/og/ */
  ogImage: string | null;
  /** All multi-art AI-generated options */
  multiArt: MultiArtOption[];
  /** Best small image for card thumbnails */
  thumbnail: string | null;
}

const EMPTY: ArticleImages = {
  heroImage: null,
  articleJpg: null,
  articleSvg: null,
  ogImage: null,
  multiArt: [],
  thumbnail: null,
};

/**
 * Look up all available images for an article slug.
 * Data comes from the pre-built manifest (no fs calls at runtime).
 */
export function discoverArticleImages(slug: string): ArticleImages {
  const entry = (manifest as Record<string, ArticleImages>)[slug];
  return entry ?? EMPTY;
}
