/** @type {import('next-sitemap').IConfig} */

function normalizeSiteUrl(rawUrl) {
  const defaultSiteUrl = 'https://alexwelcing.com'
  if (!rawUrl) {
    return defaultSiteUrl
  }
  try {
    const parsedUrl = new URL(rawUrl)
    if (parsedUrl.hostname === 'www.alexwelcing.com') {
      parsedUrl.hostname = 'alexwelcing.com'
    }
    parsedUrl.pathname = parsedUrl.pathname.replace(/\/+$/, '')
    parsedUrl.search = ''
    parsedUrl.hash = ''
    return parsedUrl.toString().replace(/\/$/, '')
  } catch {
    return defaultSiteUrl
  }
}

const siteUrl = normalizeSiteUrl(
  process.env.SITE_URL || process.env.NEXT_PUBLIC_SITE_URL || 'https://alexwelcing.com'
)

module.exports = {
  siteUrl,
  generateRobotsTxt: false, // We have a manual robots.txt in public/
  generateIndexSitemap: true,
  changefreq: 'daily',
  priority: 0.7,
  sitemapSize: 7000,

  // ============================================================
  // FIX #1: Exclude admin, chat, experiment, and draft pages
  // These were leaking into the sitemap and wasting crawl budget
  // ============================================================
  exclude: [
    '/api/*',
    '/404',
    '/admin/*',        // Admin pages should never be indexed
    '/chat',           // Interactive chat page - not indexable content
    '/drafts/*',       // Draft content
    '/experiments/*',  // Experimental pages
  ],

  transform: async (config, path) => {
    // Custom priority for important pages based on SEO strategy
    let priority = 0.7
    let changefreq = 'daily'

    // Core pages - highest priority
    if (path === '/') {
      priority = 1.0
      changefreq = 'daily'
    }
    // Hub pages - high priority (PageRank concentrators)
    else if (
      path === '/speculative-ai' ||
      path === '/agent-futures' ||
      path === '/emergent-intelligence'
    ) {
      priority = 0.95
      changefreq = 'weekly'
    }
    // About page
    else if (path === '/about') {
      priority = 0.9
      changefreq = 'monthly'
    }
    // Hire me page - recruiter focused
    else if (path === '/hire-me') {
      priority = 0.95
      changefreq = 'weekly'
    }
    // Articles index
    else if (path === '/articles') {
      priority = 0.85
      changefreq = 'daily'
    }
    // Individual articles
    else if (path.startsWith('/articles/')) {
      priority = 0.8
      changefreq = 'weekly'
    }

    return {
      loc: path,
      changefreq,
      priority,
      lastmod: config.autoLastmod ? new Date().toISOString() : undefined,
    }
  },

  // ============================================================
  // FIX #2: Only reference sitemaps that actually exist
  // REMOVED sitemap-core.xml and sitemap-articles.xml from
  // robotsTxtOptions.additionalSitemaps - these were never
  // generated, causing 404s in the sitemap index and wasting
  // Google's crawl budget on broken sitemap URLs.
  //
  // The video-sitemap.xml IS generated by scripts/generate-video-sitemap.ts
  // so it stays.
  // ============================================================
  additionalSitemaps: [
    `${siteUrl}/video-sitemap.xml`,
  ],

  robotsTxtOptions: {
    policies: [
      {
        userAgent: '*',
        allow: '/',
        disallow: ['/api/', '/drafts/', '/experiments/', '/_next/', '/admin/'],
      },
    ],
    // FIX: Removed phantom sitemap references that were causing 404s
    // Only reference sitemaps that are actually generated
    additionalSitemaps: [
      `${siteUrl}/video-sitemap.xml`,
    ],
  },
}
