import * as dotenv from 'dotenv'
import * as fs from 'fs'
import * as path from 'path'
import * as readline from 'readline'
import { Configuration, OpenAIApi } from 'openai'

dotenv.config()

if (!process.env.OPENAI_API_KEY) {
  console.error('Error: OPENAI_API_KEY is not set in .env file')
  process.exit(1)
}

const configuration = new Configuration({
  apiKey: process.env.OPENAI_API_KEY,
})
const openai = new OpenAIApi(configuration)

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
})

const articlesDir = path.join(process.cwd(), 'pages', 'docs', 'articles')

// Ensure directory exists
if (!fs.existsSync(articlesDir)) {
  fs.mkdirSync(articlesDir, { recursive: true })
}

const askQuestion = (query: string): Promise<string> => {
  return new Promise((resolve) => rl.question(query, resolve))
}

const generateArticle = async () => {
  console.log('\n--- AI Article Generator ---\n')
  console.log('Use this tool to auto-generate MDX articles for your Next.js site.')
  console.log(`Output directory: ${articlesDir}\n`)
  
  while (true) {
    const topic = await askQuestion('Enter a topic for the article (or "exit" to quit): ')
    
    if (topic.toLowerCase() === 'exit' || !topic.trim()) {
      break
    }

    console.log(`\n🤖 Generating article for topic: "${topic}"...`)
    console.log('   (This uses GPT-4 and may take 30-60 seconds)\n')

    try {
      const response = await openai.createChatCompletion({
        model: 'gpt-4',
        messages: [
          {
            role: 'system',
            content: `You are Alex Welcing, a Senior AI Product Manager, visionary tech columnist, and thought leader. 
            Write a thought-provoking, editorial-style article in MDX format about the provided topic.
            
            The article must include:
            1. A YAML Frontmatter block at the very top with:
               - title: [Creative & Engaging Title]
               - author: ["Alex Welcing"] (MUST be a JSON-style list of strings, even if only one author)
               - date: [Current Date YYYY-MM-DD]
               - description: [Compelling summary for SEO]
               - keywords: [Array of 5-7 keywords]
            
            2. Content Structure:
               - Narrative Introduction: Hook the reader with a story, specific event, or bold claim.
               - In-depth Analysis: Explore the nuance, the "grey areas," and the implications. Move beyond the obvious.
               - "The Pivot" / Unique Insight: Offer a perspective that contradicts conventional wisdom.
               - Strategic Takeaways: Actionable advice for leaders and builders.
               - Conclusion: A lingering thought or call to build better.
            
            Tone: Editorial, sophisticated, creative, and forward-looking. Use strong analogies, storytelling, and a distinct voice. Avoid corporate jargon and "marketing fluff". It should feel written by a human expert with a strong opinion, not a textbook.
            
            Format: Standard MDX.
            Code Snippets: Optional. Only use them if they brilliantly illustrate a philosophical or technical point.
            Do not wrap the output in markdown code blocks like \`\`\`markdown ... \`\`\`. Return the raw MDX content directly.
            `
          },
          {
            role: 'user',
            content: `Topic: ${topic}\nDate: ${new Date().toISOString().split('T')[0]}`
          }
        ],
        temperature: 0.85,
        max_tokens: 2500,
      })

      let content = response.data.choices[0].message?.content
      
      if (!content) {
        console.error('❌ Error: No content generated by OpenAI.')
        continue
      }

      // Cleanup: Remove any wrapping code blocks if the model accidentally added them
      content = content.replace(/^```markdown\n/, '').replace(/^```mdx\n/, '').replace(/```$/, '')

      // Extract title for filename
      const titleMatch = content.match(/title:\s*["'](.+?)["']/)
      const title = titleMatch ? titleMatch[1] : topic
      const slug = title
        .toLowerCase()
        .replace(/[^a-z0-9]+/g, '-')
        .replace(/(^-|-$)/g, '')
      
      const filename = `${slug}.mdx`
      const filePath = path.join(articlesDir, filename)

      fs.writeFileSync(filePath, content)
      
      console.log(`\n✅ Article successfully saved!`)
      console.log(`   File: ${filename}`)
      console.log(`   Path: ${filePath}`)
      
    } catch (error: any) {
      console.error('\n❌ Error generating article:')
      if (error.response) {
        console.error(`   Status: ${error.response.status}`)
        console.error(`   Message: ${JSON.stringify(error.response.data)}`)
      } else {
        console.error(`   Message: ${error.message}`)
      }
    }

    const cont = await askQuestion('\nGenerate another article? (y/n): ')
    if (cont.toLowerCase() !== 'y') {
      break
    }
    console.log('') // Newline
  }

  console.log('\nExiting. Good luck with the SEO!')
  rl.close()
  process.exit(0)
}

generateArticle()
